package com.verich.padel.common.jpa.exception.nullfield;

import java.lang.reflect.Field;
import com.verich.padel.common.jpa.exception.MkJpaNullFieldException;
import lombok.Getter;

@Getter
public class MkJpaAutogeneratedNullIdException extends MkJpaNullFieldException {

  private static final long serialVersionUID = 1L;

  final String idName;

  public MkJpaAutogeneratedNullIdException(final Field id) {
    idName = id.getName();
  }

}
